# -*- coding: utf-8 -*-
# Corpo do PDF — Briefing Andréa Rosa Souza (capa gerada separadamente via HTML)
import os, sys
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                TableStyle, KeepTogether, HRFlowable, CondPageBreak)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

PDF_SKILL_DIR = "/home/flow/.zcode/cli/plugins/cache/zcode-plugins-official/document-skills/0.1.0/skills/pdf"
sys.path.insert(0, os.path.join(PDF_SKILL_DIR, "scripts"))
from pdf import install_font_fallback

FONT_DIR = "/usr/share/fonts/truetype/liberation"
pdfmetrics.registerFont(TTFont("LiberationSerif", f"{FONT_DIR}/LiberationSerif-Regular.ttf"))
pdfmetrics.registerFont(TTFont("LiberationSerif-Bold", f"{FONT_DIR}/LiberationSerif-Bold.ttf"))
pdfmetrics.registerFont(TTFont("LiberationSerif-Italic", f"{FONT_DIR}/LiberationSerif-Italic.ttf"))
registerFontFamily("LiberationSerif", normal="LiberationSerif",
                   bold="LiberationSerif-Bold", italic="LiberationSerif-Italic")
install_font_fallback()

# ━━ Color Palette (auto-generated by pdf.py palette.generate) ━━
ACCENT       = colors.HexColor('#207591')
TEXT_PRIMARY  = colors.HexColor('#252321')
TEXT_MUTED    = colors.HexColor('#7a766f')
BG_SURFACE   = colors.HexColor('#e7e3dd')

OUT = "/home/flow/TM-System/Condado/psicologa/build/body.pdf"
os.makedirs(os.path.dirname(OUT), exist_ok=True)

MARGIN = 2.2 * cm
doc = SimpleDocTemplate(OUT, pagesize=A4,
                        leftMargin=MARGIN, rightMargin=MARGIN,
                        topMargin=2.0 * cm, bottomMargin=2.0 * cm,
                        title="Briefing — Andréa Rosa Souza · Psicóloga · Landing Page",
                        author="Z.ai", creator="Z.ai",
                        subject="Briefing de projeto de landing page")
AVAIL = A4[0] - 2 * MARGIN

h1 = ParagraphStyle('H1', fontName='LiberationSerif', fontSize=17, leading=22,
                    textColor=ACCENT, spaceBefore=18, spaceAfter=4)
h2 = ParagraphStyle('H2', fontName='LiberationSerif', fontSize=13, leading=17,
                    textColor=TEXT_PRIMARY, spaceBefore=14, spaceAfter=6)
body = ParagraphStyle('Body', fontName='LiberationSerif', fontSize=10.5, leading=16,
                      textColor=TEXT_PRIMARY, alignment=TA_JUSTIFY, spaceAfter=8)
bullet = ParagraphStyle('Bullet', parent=body, leftIndent=14, spaceAfter=4)
quote = ParagraphStyle('Quote', fontName='LiberationSerif-Italic', fontSize=10.5,
                       leading=16, leftIndent=24, textColor=TEXT_PRIMARY,
                       spaceBefore=2, spaceAfter=8)
caption = ParagraphStyle('Caption', fontName='LiberationSerif', fontSize=8.5,
                         leading=11, textColor=TEXT_MUTED, alignment=TA_CENTER)
th = ParagraphStyle('TH', fontName='LiberationSerif', fontSize=10.5, leading=14,
                    textColor=colors.white, alignment=TA_LEFT)
td = ParagraphStyle('TD', fontName='LiberationSerif', fontSize=10, leading=14,
                    textColor=TEXT_PRIMARY, alignment=TA_LEFT)
stat_style = ParagraphStyle('StatBig', fontName='LiberationSerif', fontSize=20,
                            leading=24, textColor=ACCENT, alignment=TA_CENTER)
label_style = ParagraphStyle('StatLabel', fontName='LiberationSerif', fontSize=9,
                             leading=12, textColor=TEXT_MUTED, alignment=TA_CENTER)

def section(title):
    return [CondPageBreak(100),
            Paragraph('<b>%s</b>' % title, h1),
            HRFlowable(width='100%', thickness=1.0, color=ACCENT, spaceAfter=10)]

story = []

# ── 1. Perfil ──
story += section('1. Perfil')
story.append(Paragraph(
    '<b>Andréa Rosa Souza</b> — Psicóloga clínica (CRP 06/136303), com mais de 10 anos de '
    'experiência. Atua na clínica <b>Transformação & Equilíbrio</b>, no Tatuapé, São Paulo, '
    'com atendimento presencial e online. O público atendido são adultos e jovens a partir dos '
    '14 anos, e casais. O atendimento é somente particular.', body))
story.append(Paragraph('<b>Formação:</b> Especialista em Saúde Mental (UNIP) · Terapia do Esquema '
    '(Grupo Wainer, NJ/NYC) · Psicologia Analítica (Instituto Freedom) · Extensão em dependência '
    'química (UNIFESP) · Perdas e Luto · Avaliação para Cirurgia Bariátrica · Neurociência.', body))
story.append(Spacer(1, 10))

stat_data = [[
    Table([[Paragraph('<b>10+ anos</b>', stat_style)], [Paragraph('de experiência clínica', label_style)]],
          colWidths=[AVAIL * 0.28]),
    Table([[Paragraph('<b>5,0 / 5</b>', stat_style)], [Paragraph('média em 70 avaliações', label_style)]],
          colWidths=[AVAIL * 0.28]),
    Table([[Paragraph('<b>2</b>', stat_style)], [Paragraph('selos Doctoralia Best Quality (2019 e 2020)', label_style)]],
          colWidths=[AVAIL * 0.34]),
]]
stats = Table(stat_data, colWidths=[AVAIL * 0.30, AVAIL * 0.30, AVAIL * 0.36], hAlign='CENTER')
for cell_tbl in stat_data[0]:
    cell_tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), BG_SURFACE),
        ('BOX', (0, 0), (-1, -1), 0.8, ACCENT),
        ('TOPPADDING', (0, 0), (-1, 0), 8), ('BOTTOMPADDING', (0, -1), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 6), ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]))
stats.setStyle(TableStyle([('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                           ('ALIGN', (0, 0), (-1, -1), 'CENTER')]))
story.append(stats)
story.append(Spacer(1, 10))

story.append(Paragraph('<b>Posicionamento de tom:</b> acolhimento em primeiro lugar, técnica como '
    'sustentação. Nem clínico-frio, nem emocional demais.', body))
pos_quote = Table([[Paragraph('"Espaço seguro e acolhedor — presencial ou online — para resgatar o '
    'equilíbrio emocional com sensibilidade e embasamento técnico."', quote)]],
    colWidths=[AVAIL])
pos_quote.setStyle(TableStyle([
    ('LINEBEFORE', (0, 0), (0, -1), 2, ACCENT),
    ('LEFTPADDING', (0, 0), (-1, -1), 12),
    ('TOPPADDING', (0, 0), (-1, -1), 2), ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
]))
story.append(pos_quote)

# ── 2. Serviços ──
story += section('2. Serviços')
serv_rows = [
    ('Serviço', 'Foco'),
    ('Psicoterapia Individual', 'Ansiedade, depressão, luto e padrões que se repetem'),
    ('Terapia de Casal', 'Conflitos, distanciamento e comunicação'),
    ('Avaliação Psicológica p/ Cirurgia Bariátrica', 'Com laudo — diferencial de nicho'),
    ('Online e Presencial', 'Flexibilidade de formato'),
]
tbl_data = [[Paragraph('<b>%s</b>' % serv_rows[0][0], th), Paragraph('<b>%s</b>' % serv_rows[0][1], th)]]
for a, b in serv_rows[1:]:
    tbl_data.append([Paragraph('<b>%s</b>' % a, td), Paragraph(b, td)])
col_w = [AVAIL * 0.42, AVAIL * 0.58]
serv_tbl = Table(tbl_data, colWidths=col_w, hAlign='CENTER', repeatRows=1)
style_cmds = [
    ('BACKGROUND', (0, 0), (-1, 0), ACCENT),
    ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 8), ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ('TOPPADDING', (0, 0), (-1, -1), 6), ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]
for i in range(1, len(tbl_data)):
    style_cmds.append(('BACKGROUND', (0, i), (-1, i), colors.white if i % 2 == 1 else BG_SURFACE))
serv_tbl.setStyle(TableStyle(style_cmds))
story.append(Spacer(1, 8))
story.append(serv_tbl)
story.append(Spacer(1, 6))
story.append(Paragraph('Tabela 1 — Os quatro blocos de serviço da landing page.', caption))
story.append(Spacer(1, 10))

# ── 3. Prova social ──
story += section('3. Prova social')
story.append(Paragraph('<b>70 avaliações com média 5,0/5</b> na Doctoralia. Termos mais citados: '
    '<i>atenciosa</i>, <i>explicações detalhadas</i> e <i>pontual</i>. Selos Doctoralia Best '
    'Quality 2019 e 2020.', body))
story.append(Paragraph('<b>Trechos verificados de avaliações:</b>', body))
for q in ['"Muito atenciosa e acolhedora, com sensibilidade e clareza."',
          '"Escuta ativa... processo terapêutico sério, humano e transformador."',
          '"Profissional competente e direta. Consultório bem localizado, pontual."']:
    qt = Table([[Paragraph(q, quote)]], colWidths=[AVAIL])
    qt.setStyle(TableStyle([
        ('LINEBEFORE', (0, 0), (0, -1), 2, ACCENT),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('TOPPADDING', (0, 0), (-1, -1), 2), ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
    ]))
    story.append(qt)

# ── 4. Estrutura sugerida da LP ──
story += section('4. Estrutura sugerida da landing page')
lp_rows = [
    ('Seção', 'Conteúdo'),
    ('Hero', 'Dor reconhecível + promessa (presencial no Tatuapé ou online)'),
    ('Prova social', 'Nota, avaliações e selos'),
    ('Serviços', 'Os 4 blocos de serviço'),
    ('Sobre', 'Formação e abordagem — autoridade como reforço, não como abertura'),
    ('Como funciona', 'Contato → sessão → acompanhamento'),
    ('CTA final + rodapé', 'Chamada para agendamento, CRP e endereço'),
]
lp_data = [[Paragraph('<b>%s</b>' % lp_rows[0][0], th), Paragraph('<b>%s</b>' % lp_rows[0][1], th)]]
for a, b in lp_rows[1:]:
    lp_data.append([Paragraph('<b>%s</b>' % a, td), Paragraph(b, td)])
lp_tbl = Table(lp_data, colWidths=[AVAIL * 0.30, AVAIL * 0.70], hAlign='CENTER', repeatRows=1)
lp_style = [
    ('BACKGROUND', (0, 0), (-1, 0), ACCENT),
    ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 8), ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ('TOPPADDING', (0, 0), (-1, -1), 6), ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]
for i in range(1, len(lp_data)):
    lp_style.append(('BACKGROUND', (0, i), (-1, i), colors.white if i % 2 == 1 else BG_SURFACE))
lp_tbl.setStyle(TableStyle(lp_style))
story.append(Spacer(1, 8))
story.append(lp_tbl)
story.append(Spacer(1, 6))
story.append(Paragraph('Tabela 2 — Ordem das seções da página.', caption))

# ── 5. Perguntas para alinhamento ──
story += section('5. Perguntas para alinhamento')
story.append(Paragraph('<b>Mídias</b>', h2))
story.append(Paragraph('• Quais <b>fotos</b> você autoriza usar no site? (podemos usar as do '
    'Doctoralia/Wix? prefere enviar outras?)', bullet))
story.append(Paragraph('• Você tem <b>vídeos</b> (apresentação, Reels, depoimentos) que autoriza '
    'compartilhar na página?', bullet))
story.append(Paragraph('• Para as <b>imagens criativas</b> (composição visual da página), prefere '
    'fotos reais do consultório ou imagens de banco de fotos?', bullet))
story.append(Paragraph('• <b>Site de referência:</b> https://psicologaantoniabrandao.com.br/ — '
    'aguardando confirmação.', bullet))
story.append(Paragraph('<b>Estratégia</b>', h2))
story.append(Paragraph('• <b>Agendamento:</b> prefere que o botão principal aponte para o '
    '<b>Doctoralia</b> (agendamento automático, escolha de horário sem troca de mensagens) ou para '
    'o <b>WhatsApp</b> (contato mais direto)? <i>Sugestão: Doctoralia como principal, WhatsApp '
    'como alternativa.</i>', bullet))
story.append(Paragraph('• <b>Tom da página:</b> reforçar mais a <b>autoridade técnica</b> '
    '(formações, 10 anos, nota 5,0) ou o <b>acolhimento</b> (quem chega sobrecarregado se sente '
    'compreendido)? <i>Sugestão: acolhimento na entrada da página, autoridade como validação no '
    'meio — equilibra e converte nos dois perfis de paciente.</i>', bullet))

doc.build(story)
print("OK:", OUT)
